title: LUONG CHUOC MINH
theme: jekyll-theme-minimal # Hoặc tên theme bạn đang dùng
logo: "/images/logo.jpg?raw=true"

description: |
  <p align="center">
    <b>Software Engineering Student @ Saigon University</b>
  </p>

  <p align="center">
    <img src="https://img.shields.io/badge/Birthday-Dec%2026%2C%202005-orange?style=flat-square&logo=cakephp&logoColor=white">
    <a href="tel:0898992485"><img src="https://img.shields.io/badge/Phone-0898.992.485-green?style=flat-square&logo=whatsapp"></a>
    <a href="mailto:nguyenminhzz283@gmail.com"><img src="https://img.shields.io/badge/Email-nguyenminhzz283@gmail.com-blue?style=flat-square&logo=gmail"></a>
  </p>

  <p align="center">
    <a href="https://www.linkedin.com/in/l%C6%B0%C6%A1ng-minh-43ab9837a/"><img src="https://img.shields.io/badge/LinkedIn-Connect-blue?style=flat-square&logo=linkedin"></a>
    <a href="https://github.com/muabang123"><img src="https://img.shields.io/badge/GitHub-Follow-black?style=flat-square&logo=github"></a>
  </p>
